language: go

go: 1.4

script:
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - test -z "$(go fmt)"
    - go vet
    - go test
    - go test -race
    - test -z "$(goimports -l .)"

before_install:
    - go get golang.org/x/tools/cmd/vet golang.org/x/tools/cmd/goimports
